x-base: &base
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  <<: *base
  channel_prefix: quote_editor_development
  # adapter: async

test:
  adapter: test

production:
  <<: *base
  channel_prefix: quote_editor_production
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: quote_editor_production
